Tech-debt: Rubocop tidy
ministryofjustice/laa-apply-for-legal-aid pull request #2178
Opened 2021-01-15 09:47 UTC by colinbruce

## What

Semi-regular attempt to reduce rubocop todo's and disables

## Checklist

Before you ask people to review this PR:

- [ ] Tests and rubocop should be passing: `bundle exec rake`
- [ ] Github should not be reporting conflicts; you should have recently run `git rebase master`.
- [ ] There should be no unnecessary whitespace changes. These make diffs harder to read and conflicts more likely.
- [ ] The PR description should say what you changed and why, with a link to the JIRA story.
- [ ] You should have looked at the diff against master and ensured that nothing unexpected is included in your changes.
- [ ] You should have checked that the commit messages say why the change was made.

2021-01-15 15:38 UTC, colinbruce commented
As I'll be on leave if someone does review this, can they merge it too?
Ta :+1:

2021-01-18 13:08 UTC, Alex-Swann commented on app/models/ccms/submission.rb
> +      service = STATE_SERVICES[aasm_state.to_s]
We could do `aasm_state.to_sym` if we don't know if `aasm_state` comes in as a sym which might be nicer as then we could convert all `STATE_SERVICES` keys to syms instead

2021-01-18 13:10 UTC, Alex-Swann commented on app/services/ccms/payload_generators/entity_attributes_generator.rb
> +        method_to_call = RESPONSE_TYPES[config[:response_type]]
sym response_type and use RESPONSE_TYPES keys as syms

2021-01-18 13:11 UTC, Alex-Swann commented on app/services/ccms/payload_generators/entity_attributes_generator.rb
> +      # def extract_response_value(config)
I'm guessing committed in error and should be removed?

2021-01-19 09:55 UTC, Alex-Swann requested changes
A few minor comments to address.

2021-01-19 11:02 UTC, mpw5 commented
> A few minor comments to address. Might be worth someone with more in-depth rubucop knowledge reviewing and confirming they are happy with this also. If so, I can fix my own comments and get this out the door. @stephenrichards, @mpw5, @willc-work ?

@Alex-Swann This all looks good to me. Feel free to make the changes you suggested and I'll re-review when you're done.

2021-01-19 15:07 UTC, Alex-Swann approved these changes

2021-01-19 16:15 UTC, mpw5 approved these changes
LGTM

2021-01-19 21:12 UTC, merged