AP-2344 Include gateway evidence documents to ccms upload
ministryofjustice/laa-apply-for-legal-aid pull request #2612
Opened 2021-06-14 10:59 UTC by Obsiye

## AP-2344 Include gateway evidence documents to ccms upload

[Link to story](https://dsdmoj.atlassian.net/browse/AP-2344)

- Add gateway evidence document attachments to the ccms document upload process

- Test the above.

### Question for reviewer:

We thoroughly test with a statement of case attachment. Do you think these tests should be duplicated for gateway evidence? The document upload process focuses on documents attached to the application and not what type specifically.

## Checklist

Before you ask people to review this PR:

- [ ] Tests and rubocop should be passing: `bundle exec rake`
- [ ] Github should not be reporting conflicts; you should have recently run `git rebase master`.
- [ ] There should be no unnecessary whitespace changes. These make diffs harder to read and conflicts more likely.
- [ ] The PR description should say what you changed and why, with a link to the JIRA story.
- [ ] You should have looked at the diff against master and ensured that nothing unexpected is included in your changes.
- [ ] You should have checked that the commit messages say why the change was made.

2021-06-14 11:20 UTC, colinbruce requested changes
I think you need to change the document ID type too

2021-06-14 11:20 UTC, colinbruce commented on spec/services/ccms/submitters/obtain_document_id_service_spec.rb
> +              expect(admin1_documents).to eq 4
I thought the ticket said that gateway evidence should be tagged as `STATE` rather than `ADMIN1`?

2021-06-14 12:53 UTC, stephenrichards approved these changes

2021-06-15 07:56 UTC, colinbruce approved these changes
LGTM :+1:

2021-06-17 12:46 UTC, merged